id: umm
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/umm/umm.pp
  update: /etc/puppet/modules/osnailyfacter/modular/umm/umm.pp
input:
  fqdn:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
