name: composition_override_configuration
resources:
- {id: override_configuration, from: f2s/vr_override_configuration, location: '#{node}#'}
events:
- type: depends_on
  state: success
  parent:
    action: run
    with_tags: [resource=pre_hiera_config, 'node=#{node}#']
  depend_action: override_configuration#{index}#.run
