name: composition_openstack-network-server-config
resources:
- {id: openstack-network-server-config, from: f2s/vr_openstack-network-server-config,
  location: '#{node}#'}
events:
- type: depends_on
  state: success
  parent:
    action: run
    with_tags: [resource=openstack-network-common-config, 'node=#{node}#']
  depend_action: openstack-network-server-config#{index}#.run
