id: updatedb
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/ceph/updatedb.pp
  update: /etc/puppet/modules/osnailyfacter/modular/ceph/updatedb.pp
input:
  fqdn:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
  storage:
    value: null
