id: nova-db
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/openstack-controller/db.pp
  update: /etc/puppet/modules/osnailyfacter/modular/openstack-controller/db.pp
input: {}
