id: top-role-mongo
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/roles/mongo.pp
  update: /etc/puppet/modules/osnailyfacter/modular/roles/mongo.pp
input:
  fqdn:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
