id: primary-rabbitmq
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/rabbitmq/rabbitmq.pp
  update: /etc/puppet/modules/osnailyfacter/modular/rabbitmq/rabbitmq.pp
input: {}
