id: openstack-network-server-config
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/openstack-network/server-config.pp
  update: /etc/puppet/modules/osnailyfacter/modular/openstack-network/server-config.pp
input: {}
