id: openstack-network-agents-dhcp
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/openstack-network/agents/dhcp.pp
  update: /etc/puppet/modules/osnailyfacter/modular/openstack-network/agents/dhcp.pp
input:
  puppet_modules:
    type: str!
    value: /etc/puppet/modules
