id: openstack-network-agents-dhcp
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/openstack-network/agents/dhcp.pp
  update: /etc/puppet/modules/osnailyfacter/modular/openstack-network/agents/dhcp.pp
input:
  debug:
    value: null
  fqdn:
    value: null
  neutron_advanced_configuration:
    value: null
  primary_controller:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
  use_neutron:
    value: null
