id: fuel_pkgs
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/fuel_pkgs/fuel_pkgs.pp
  update: /etc/puppet/modules/osnailyfacter/modular/fuel_pkgs/fuel_pkgs.pp
input: {}
