id: netconfig
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/netconfig/netconfig.pp
  update: /etc/puppet/modules/osnailyfacter/modular/netconfig/netconfig.pp
input: {}
