id: cluster-vrouter
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/cluster-vrouter/cluster-vrouter.pp
  update: /etc/puppet/modules/osnailyfacter/modular/cluster-vrouter/cluster-vrouter.pp
input:
  puppet_modules:
    type: str!
    value: /etc/puppet/modules
