id: openstack-network-routers
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/openstack-network/routers.pp
  update: /etc/puppet/modules/osnailyfacter/modular/openstack-network/routers.pp
input: {}
