id: heat-keystone
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/heat/keystone.pp
  update: /etc/puppet/modules/osnailyfacter/modular/heat/keystone.pp
input: {}
