id: sahara-db
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/sahara/db.pp
  update: /etc/puppet/modules/osnailyfacter/modular/sahara/db.pp
input:
  puppet_modules:
    type: str!
    value: /etc/puppet/modules
