id: enable_rados
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/ceph/enable_rados.pp
  update: /etc/puppet/modules/osnailyfacter/modular/ceph/enable_rados.pp
input:
  puppet_modules:
    type: str!
    value: /etc/puppet/modules
