id: enable_rados
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/ceph/enable_rados.pp
  update: /etc/puppet/modules/osnailyfacter/modular/ceph/enable_rados.pp
input:
  fqdn:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
