id: heat-db
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/heat/db.pp
  update: /etc/puppet/modules/osnailyfacter/modular/heat/db.pp
input:
  database_vip:
    value: null
  fqdn:
    value: null
  heat:
    value: null
  management_vip:
    value: null
  mysql:
    value: null
  mysql_custom_setup_class:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
