id: primary-ceph-radosgw
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/ceph/radosgw.pp
  update: /etc/puppet/modules/osnailyfacter/modular/ceph/radosgw.pp
input:
  puppet_modules:
    type: str!
    value: /etc/puppet/modules
