id: dns-client
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/dns/dns-client.pp
  update: /etc/puppet/modules/osnailyfacter/modular/dns/dns-client.pp
input: {}
