id: reserved_ports
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/netconfig/reserved_ports.pp
  update: /etc/puppet/modules/osnailyfacter/modular/netconfig/reserved_ports.pp
input: {}
