id: conntrackd
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/virtual_ips/conntrackd.pp
  update: /etc/puppet/modules/osnailyfacter/modular/virtual_ips/conntrackd.pp
input:
  puppet_modules:
    type: str!
    value: /etc/puppet/modules
