id: connectivity_tests
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/netconfig/connectivity_tests.pp
  update: /etc/puppet/modules/osnailyfacter/modular/netconfig/connectivity_tests.pp
input:
  fqdn:
    value: null
  puppet_modules:
    value: null
  repo_setup:
    value: null
  role:
    value: null
