id: configure_default_route
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/netconfig/configure_default_route.pp
  update: /etc/puppet/modules/osnailyfacter/modular/netconfig/configure_default_route.pp
input: {}
