id: openstack-network-compute-nova
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/openstack-network/compute-nova.pp
  update: /etc/puppet/modules/osnailyfacter/modular/openstack-network/compute-nova.pp
input:
  puppet_modules:
    type: str!
    value: /etc/puppet/modules
