id: openstack-network-compute-nova
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/openstack-network/compute-nova.pp
  update: /etc/puppet/modules/osnailyfacter/modular/openstack-network/compute-nova.pp
input:
  fqdn:
    value: null
  management_vip:
    value: null
  neutron_config:
    value: null
  neutron_endpoint:
    value: null
  nova:
    value: null
  puppet_modules:
    value: null
  region:
    value: null
  role:
    value: null
  service_endpoint:
    value: null
  use_neutron:
    value: null
