id: dump_rabbitmq_definitions
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/astute/dump_rabbitmq_definitions.pp
  update: /etc/puppet/modules/osnailyfacter/modular/astute/dump_rabbitmq_definitions.pp
input: {}
