id: top-role-compute-vmware
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/vmware/compute-vmware.pp
  update: /etc/puppet/modules/osnailyfacter/modular/vmware/compute-vmware.pp
input:
  fqdn:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
