id: ironic-conductor
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/roles/ironic-conductor.pp
  update: /etc/puppet/modules/osnailyfacter/modular/roles/ironic-conductor.pp
input:
  fqdn:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
