id: neutron-keystone
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/openstack-network/keystone.pp
  update: /etc/puppet/modules/osnailyfacter/modular/openstack-network/keystone.pp
input: {}
