id: vmware-vcenter
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/vmware/vcenter.pp
  update: /etc/puppet/modules/osnailyfacter/modular/vmware/vcenter.pp
input: {}
