id: horizon
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/horizon/horizon.pp
  update: /etc/puppet/modules/osnailyfacter/modular/horizon/horizon.pp
input: {}
