id: apache
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/apache/apache.pp
  update: /etc/puppet/modules/osnailyfacter/modular/apache/apache.pp
input:
  apache_ports:
    value: null
  fqdn:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
