id: globals
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/globals/globals.pp
  update: /etc/puppet/modules/osnailyfacter/modular/globals/globals.pp
input:
  puppet_modules:
    type: str!
    value: /etc/puppet/modules
