id: ceilometer-compute
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/ceilometer/compute.pp
  update: /etc/puppet/modules/osnailyfacter/modular/ceilometer/compute.pp
input: {}
