id: ironic-compute
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/ironic/ironic-compute.pp
  update: /etc/puppet/modules/osnailyfacter/modular/ironic/ironic-compute.pp
input: {}
