id: openstack-haproxy-glance
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/openstack-haproxy/openstack-haproxy-glance.pp
  update: /etc/puppet/modules/osnailyfacter/modular/openstack-haproxy/openstack-haproxy-glance.pp
input:
  fqdn:
    value: null
  glance:
    value: null
  glance_ipaddresses:
    value: null
  glance_names:
    value: null
  management_vip:
    value: null
  network_metadata:
    value: null
  public_ssl:
    value: null
  public_vip:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
