id: openstack-haproxy-stats
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/openstack-haproxy/openstack-haproxy-stats.pp
  update: /etc/puppet/modules/osnailyfacter/modular/openstack-haproxy/openstack-haproxy-stats.pp
input:
  database_vip:
    value: null
  fqdn:
    value: null
  management_vip:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
  service_endpoint:
    value: null
