id: enable_cinder_volume_service
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/astute/enable_cinder.pp
  update: /etc/puppet/modules/osnailyfacter/modular/astute/enable_cinder.pp
input: {}
