id: ceph_create_pools
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/ceph/ceph_pools.pp
  update: /etc/puppet/modules/osnailyfacter/modular/ceph/ceph_pools.pp
input:
  fqdn:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
  storage:
    value: null
