id: ntp-check
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/ntp/ntp-check.pp
  update: /etc/puppet/modules/osnailyfacter/modular/ntp/ntp-check.pp
input:
  puppet_modules:
    type: str!
    value: /etc/puppet/modules
