id: disable_keystone_service_token
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/astute/service_token_off.pp
  update: /etc/puppet/modules/osnailyfacter/modular/astute/service_token_off.pp
input:
  fqdn:
    value: null
  keystone_hash:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
