id: glance
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/glance/glance.pp
  update: /etc/puppet/modules/osnailyfacter/modular/glance/glance.pp
input:
  puppet_modules:
    type: str!
    value: /etc/puppet/modules
