id: ceph-compute
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/ceph/ceph_compute.pp
  update: /etc/puppet/modules/osnailyfacter/modular/ceph/ceph_compute.pp
input: {}
