id: controller_remaining_tasks
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/roles/controller.pp
  update: /etc/puppet/modules/osnailyfacter/modular/roles/controller.pp
input: {}
