id: create-cinder-types
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/openstack-cinder/create_cinder_types.pp
  update: /etc/puppet/modules/osnailyfacter/modular/openstack-cinder/create_cinder_types.pp
input:
  puppet_modules:
    type: str!
    value: /etc/puppet/modules
