id: ssl-add-trust-chain
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/ssl/ssl_add_trust_chain.pp
  update: /etc/puppet/modules/osnailyfacter/modular/ssl/ssl_add_trust_chain.pp
input:
  fqdn:
    value: null
  public_ssl:
    value: null
  public_vip:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
