id: primary-database
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/database/database.pp
  update: /etc/puppet/modules/osnailyfacter/modular/database/database.pp
input: {}
