id: ironic-api
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/ironic/ironic.pp
  update: /etc/puppet/modules/osnailyfacter/modular/ironic/ironic.pp
input:
  ironic:
    value: null
  puppet_modules:
    value: null
