id: openstack-network-plugins-l2
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/openstack-network/plugins/ml2.pp
  update: /etc/puppet/modules/osnailyfacter/modular/openstack-network/plugins/ml2.pp
input:
  puppet_modules:
    type: str!
    value: /etc/puppet/modules
