id: public_vip_ping
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/virtual_ips/public_vip_ping.pp
  update: /etc/puppet/modules/osnailyfacter/modular/virtual_ips/public_vip_ping.pp
input: {}
