id: pre_hiera_config
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/hiera/hiera.pp
  update: /etc/puppet/modules/osnailyfacter/modular/hiera/hiera.pp
input: {}
