id: openstack-network-common-config
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/openstack-network/common-config.pp
  update: /etc/puppet/modules/osnailyfacter/modular/openstack-network/common-config.pp
input:
  puppet_modules:
    type: str!
    value: /etc/puppet/modules
