id: keystone-db
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/keystone/db.pp
  update: /etc/puppet/modules/osnailyfacter/modular/keystone/db.pp
input:
  database_vip:
    value: null
  fqdn:
    value: null
  keystone:
    value: null
  mysql:
    value: null
  mysql_custom_setup_class:
    value: null
  network_metadata:
    value: null
  node_name:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
