id: virtual_ips
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/virtual_ips/virtual_ips.pp
  update: /etc/puppet/modules/osnailyfacter/modular/virtual_ips/virtual_ips.pp
input:
  fqdn:
    value: null
  network_metadata:
    value: null
  network_scheme:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
