id: top-role-cinder-vmware
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/vmware/cinder-vmware.pp
  update: /etc/puppet/modules/osnailyfacter/modular/vmware/cinder-vmware.pp
input:
  puppet_modules:
    type: str!
    value: /etc/puppet/modules
