id: glance-keystone
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/glance/keystone.pp
  update: /etc/puppet/modules/osnailyfacter/modular/glance/keystone.pp
input:
  fqdn:
    value: null
  glance:
    value: null
  management_vip:
    value: null
  public_ssl:
    value: null
  public_vip:
    value: null
  puppet_modules:
    value: null
  region:
    value: null
  role:
    value: null
