id: glance-keystone
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/glance/keystone.pp
  update: /etc/puppet/modules/osnailyfacter/modular/glance/keystone.pp
input: {}
