id: openstack-network-networks
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/openstack-network/networks.pp
  update: /etc/puppet/modules/osnailyfacter/modular/openstack-network/networks.pp
input:
  access:
    value: null
  fqdn:
    value: null
  neutron_config:
    value: null
  primary_controller:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
  use_neutron:
    value: null
