id: murano-rabbitmq
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/murano/rabbitmq.pp
  update: /etc/puppet/modules/osnailyfacter/modular/murano/rabbitmq.pp
input:
  fqdn:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
