id: logging
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/logging/logging.pp
  update: /etc/puppet/modules/osnailyfacter/modular/logging/logging.pp
input:
  puppet_modules:
    type: str!
    value: /etc/puppet/modules
