id: openstack-haproxy
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/openstack-haproxy/openstack-haproxy.pp
  update: /etc/puppet/modules/osnailyfacter/modular/openstack-haproxy/openstack-haproxy.pp
input:
  fqdn:
    value: null
  puppet_modules:
    value: null
  role:
    value: null
