id: primary-dns-server
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/dns/dns-server.pp
  update: /etc/puppet/modules/osnailyfacter/modular/dns/dns-server.pp
input: {}
