id: primary-openstack-network-agents-metadata
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/openstack-network/agents/metadata.pp
  update: /etc/puppet/modules/osnailyfacter/modular/openstack-network/agents/metadata.pp
input:
  puppet_modules:
    type: str!
    value: /etc/puppet/modules
