id: update_hosts
handler: puppetv2
version: '8.0'
actions:
  run: /etc/puppet/modules/osnailyfacter/modular/hosts/hosts.pp
  update: /etc/puppet/modules/osnailyfacter/modular/hosts/hosts.pp
input: {}
